apiVersion: v1
kind: Service
metadata:
  name: redis-pod
spec:
  containers:
    - name: demo-cont
      image: islajd/test:fisttry
      ports:
        - containerPort: 6300
  type: NodePort